### ISSUE TITLE
Studio1902\PeakTools\Jobs\UpdateMissingAltCacheJob has been attempted too many times.

### ISSUE THREAD

**Issue by exophunk** [studio1902/statamic-peak-tools#17]
### Bug description

Our Flare Error page flags a lot of incidents, where the "UpdateMissingAltCacheJob" is being attempted too often. I don't know why exactly it fails or is attempted too often.

The thing is, we don't use the "Missing Alt Widget". Is there a way to easily disable the events dispatching this job? I assume when we're not using the widget, we also don't need to run that job at all?

https://flareapp.io/share/lm2vR8Em

Maybe I can overwrite the events registered or so? I'm not sure how I would remove the listeners. Maybe you could also add a config flag to disable it?

### How to reproduce

Not sure though

### Logs

```shell
https://flareapp.io/share/lm2vR8Em
```

### Environment

```yaml
Laravel Version: 10.43.0
PHP Version: 8.2.9
Composer Version: 2.7.1
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / daily, important, flare
Mail: mandrill
Queue: redis
Session: redis

Livewire
Livewire: v3.4.4

Statamic
Addons: 14
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: full
Version: 4.48.0 PRO

Statamic Addons
...
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 2.6.2
studio1902/statamic-peak-tools: 3.4.3
...
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
